### PR TITLE
Update d/ch for 6.2.0-1~ibmcloud0.1 release

### PR DESCRIPTION
**Pull request by utkarsh2102**
Hello,

We have a new upstream release (thank you, @THS-on for prepping this!). Before I roll this out, I'd like to request if you both, @mirespace and @THS-on, can test this release to make sure everything's good and (still) working?

Ideally, I'd like to know if Ubuntu Bionic still works (except for the known issue #11). We've added `python3-packaging` and `python-psutil` which are a bit older in Bionic (18.04) and so I'm interested to see if those versions are OK as well.

Let me know if you have any questions or concerns. Thank you!

### CODE REVIEW

**Comment by mirespace** [comment]
I made an upgrade from the previous version  and it install smoothñy, but registrar and verifier service fails due to : 

``
AttributeError: module 'ssl' has no attribute 'TLSVersion'

``
Checking SSL version and python requisites (I found that attribute at python3.8 but python --version returns 3.6)

**Comment by utkarsh2102** [comment]
> `AttributeError: module 'ssl' has no attribute 'TLSVersion'`

Thank you for reporting! Does that come from the new `Lib/ssl.py` from CPython?

**Review by THS-on — APPROVED** [review]
Works fine on Debian 11.

**Comment by THS-on** [comment]
In general also CentOS 8 still uses also Python 3.6 and Keylime might tries to support it, so that we can reduce the patches to make Keylime work with Python 3.6. @utkarsh2102 If you look in the Keylime slack there is a discussion on what version should be targeted.

**Comment by utkarsh2102** [comment]
> @utkarsh2102 If you look in the Keylime slack there is a discussion on what version should be targeted.

Ooh, thanks! Just checked, makes sense!

**Comment by mirespace** [comment]
Doing changes to adapt keylime code to python3.6's ssl ... other cases are arising when fixing the already known ones. WIP.

**Comment by THS-on** [comment]
@mirespace if those changes don't include bundling whole Python modules please send them also upstream.

**Comment by mirespace** [comment]
Following this: https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TLSv1 I made a patch that in testing is ok:

```
root@bionic-keylime-split:~# systemctl status keylime_registrar
● keylime_registrar.service - The Keylime registrar service
   Loaded: loaded (/lib/systemd/system/keylime_registrar.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/keylime_registrar.service.d
           └─zzz-lxc-service.conf
   Active: active (running) since Mon 2021-09-13 06:13:54 UTC; 6s ago
 Main PID: 31464 (keylime_registr)
    Tasks: 3 (limit: 1113)
   CGroup: /system.slice/keylime_registrar.service
           └─31464 /usr/bin/python3 /usr/bin/keylime_registrar

Sep 13 06:13:54 bionic-keylime-split systemd[1]: Started The Keylime registrar service.
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: Using config file /etc/keylime.conf
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.668 - keylime.keylime_db - INFO -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.743 - keylime.keylime_db - INFO -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.746 - alembic.env - INFO - Migrat
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.747 - alembic.runtime.migration -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.748 - alembic.runtime.migration -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.756 - keylime.cloudverifier_commo
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.758 - keylime.registrar - INFO - 
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.758 - keylime.registrar - INFO - 
root@bionic-keylime-split:~# 
root@bionic-keylime-split:~# 
root@bionic-keylime-split:~# systemctl status keylime_registrar keylime_verifier
● keylime_registrar.service - The Keylime registrar service
   Loaded: loaded (/lib/systemd/system/keylime_registrar.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/keylime_registrar.service.d
           └─zzz-lxc-service.conf
   Active: active (running) since Mon 2021-09-13 06:13:54 UTC; 7min ago
 Main PID: 31464 (keylime_registr)
    Tasks: 3 (limit: 1113)
   CGroup: /system.slice/keylime_registrar.service
           └─31464 /usr/bin/python3 /usr/bin/keylime_registrar

Sep 13 06:13:54 bionic-keylime-split systemd[1]: Started The Keylime registrar service.
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: Using config file /etc/keylime.conf
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.668 - keylime.keylime_db - INFO -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.743 - keylime.keylime_db - INFO -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.746 - alembic.env - INFO - Migrat
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.747 - alembic.runtime.migration -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.748 - alembic.runtime.migration -
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.756 - keylime.cloudverifier_commo
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.758 - keylime.registrar - INFO - 
Sep 13 06:13:54 bionic-keylime-split keylime_registrar[31464]: 2021-09-13 06:13:54.758 - keylime.registrar - INFO - 

● keylime_verifier.service - The Keylime verifier
   Loaded: loaded (/lib/systemd/system/keylime_verifier.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/keylime_verifier.service.d
           └─zzz-lxc-service.conf
   Active: active (running) since Mon 2021-09-13 06:12:09 UTC; 9min ago
 Main PID: 31440 (keylime_verifie)
    Tasks: 5 (limit: 1113)
   CGroup: /system.slice/keylime_verifier.service
```
Doing a new PR for this...

**Comment by utkarsh2102** [comment]
@THS-on, @mirespace: re-pushed the update d/ch entry! Please TAL if all looks correct?

**Comment by THS-on** [comment]
Looks correct.

**Comment by mirespace** [comment]
Agent is not deploying keylime.conf, it's deploying keylime-agent.conf:

```
root@bionic-keylime:~/Code/Builds# l /etc/keylime*
/etc/keylime-agent.conf
root@bionic-keylime:~/Code/Builds# 
```

So it is not starting due to condition:

`ConditionPathExistsGlob=/etc/keylime.conf
`

Also, noticed that registrar do a restart of 120sec after installing.

**Comment by mirespace** [comment]
Rechecked installation... OK.

**Comment by utkarsh2102** [comment]
Thank you, both!
